package java_parminder__finl;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @parminder_sahni
 */
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import javax.swing.ButtonGroup;


public class Train extends javax.swing.JFrame {

    /**
     * Creates new form Train
     */
    public Train() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSTD = new javax.swing.JTextField();
        jType = new javax.swing.JTextField();
        jA = new javax.swing.JTextField();
        jC = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jFrom = new javax.swing.JTextField();
        jTo = new javax.swing.JTextField();
        jDate = new javax.swing.JTextField();
        jTime = new javax.swing.JTextField();
        jTicketNo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPrice = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jRoute = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRbStd = new javax.swing.JRadioButton();
        jRbEco = new javax.swing.JRadioButton();
        jRbFirst = new javax.swing.JRadioButton();
        jRbChildYes = new javax.swing.JRadioButton();
        jRbReturn = new javax.swing.JRadioButton();
        jRbAdultYes = new javax.swing.JRadioButton();
        jRbSingle = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jblTax = new javax.swing.JTextField();
        jblSubTotal = new javax.swing.JTextField();
        jblTotal = new javax.swing.JTextField();
        jbtnTotal = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jCB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(1400, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 84)); // NOI18N
        jLabel1.setText("Train Ticketing System");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\jogin_000\\Desktop\\2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Ticket Type");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Class");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Child");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Adult");

        jSTD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jType.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("From");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("To");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Date");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Time");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Ticket No.");

        jFrom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jTo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jTicketNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTicketNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTicketNoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("Price");

        jPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPriceActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("Route");

        jRoute.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRouteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSTD, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel11)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jA, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTicketNo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTicketNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Class");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Adult");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Ticket Type");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Child");

        buttonGroup3.add(jRbStd);
        jRbStd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRbStd.setText("Standard");

        buttonGroup3.add(jRbEco);
        jRbEco.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRbEco.setText("Economy");

        buttonGroup3.add(jRbFirst);
        jRbFirst.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRbFirst.setText("First Class");
        jRbFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbFirstActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRbChildYes);
        jRbChildYes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRbChildYes.setText("Yes");

        buttonGroup2.add(jRbReturn);
        jRbReturn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRbReturn.setText("Return");

        buttonGroup1.add(jRbAdultYes);
        jRbAdultYes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRbAdultYes.setText("Yes");
        jRbAdultYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbAdultYesActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRbSingle);
        jRbSingle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRbSingle.setText("Single");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Sub Total");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Tax");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Total");

        jblTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jblTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnTotalMouseClicked(evt);
            }
        });
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnExitMouseClicked(evt);
            }
        });

        jCB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kolkata", "Mumbai", "Ajmer", "Pune" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Destination");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jbtnTotal)
                                .addGap(26, 26, 26)
                                .addComponent(jbtnReset)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnExit))
                            .addComponent(jblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRbEco)
                                    .addComponent(jRbFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRbStd))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jRbReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jRbSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRbAdultYes, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRbChildYes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRbStd)
                            .addComponent(jRbSingle)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRbAdultYes)
                            .addComponent(jRbChildYes))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRbReturn)
                        .addComponent(jLabel10))
                    .addComponent(jRbEco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRbFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTotal)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jTicketNoActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jPriceActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jRouteActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jRbFirstActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        this.getContentPane().setBackground(Color.BLACK);
    }                                    

    private void jbtnExitMouseClicked(java.awt.event.MouseEvent evt) {                                      
        System.exit(0);
    }                                     

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        jblSubTotal.setText(null);
        jblTax.setText(null);
        jblTotal.setText(null);
        jTicketNo.setText(null);
        jRoute.setText(null);
        jPrice.setText(null);
        jSTD.setText(null);
        jType.setText(null);
        jA.setText(null);
        jC.setText(null);
        jFrom.setText(null);
        jTo.setText(null);
        jDate.setText(null);
        jTime.setText(null);
        
        
                
             
    
    }                                         

  
    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {                                          
       //=========================Time=====================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        jTime.setText(tTime.format(timer.getTime()));
        //=========================Date========================
          SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyy");
        jDate.setText(tDate.format(timer.getTime()));
        
        jFrom.setText("Delhi");
        jTo.setText((String) jCB.getSelectedItem());
        
        //========================Random Number generation==========
        int num1;
        String q1 = "";
        num1 = 1325+ (int) (Math.random()*4238);
        q1  += num1 + 1325;
        jTicketNo.setText(q1);
        //============================================================
        jRoute.setText("ANY");
        
        
        
    }                                         

    private void jbtnTotalMouseClicked(java.awt.event.MouseEvent evt) {                                       
        
        double tax = 19.50;
        double MilesK8 =25.78;
        double MilesK12 = 25.10;
        double MilesK20 = 45.23;
        double MilesK30 = 55.98;
        double totalCost , eco = 3.85, fclass = 5.6;
        if (((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")) )
                {
                    totalCost = (tax * MilesK8) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK8);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK8 + totalCost);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL");
                }
        
        
        else if (((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")))
        {
            
           
                    totalCost = (tax *(MilesK8)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK8 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK8 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        else if ( ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")))
        {
            
             totalCost = (tax * MilesK8) / 100;
                    String sTax = String.format("RS %.2f", totalCost - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK8);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK8 + totalCost - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK8)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK8 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK8 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
        
        else if ( ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        
        {
            
            
            totalCost = (tax * MilesK12) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK12 + totalCost);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
            
            
        }
        
        else if (((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        {
            
           
                    totalCost = (tax *(MilesK12)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK12 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        
        
        else if ( ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        {
            
             totalCost = (tax * MilesK12) / 100;
                    String sTax = String.format("RS %.2f", totalCost - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK12 + totalCost - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK12)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK12 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
       
         else if ( ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        
        {
            
            
            totalCost = (tax * MilesK20) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK20);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK20 + totalCost);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
            
            
        }
        
        else if (((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        {
            
           
                    totalCost = (tax *(MilesK20)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK12 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        
        
        else if ( ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        {
            
             totalCost = (tax * MilesK20) / 100;
                    String sTax = String.format("RS %.2f", totalCost - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK20);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK20 + totalCost - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK20)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK20 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK20 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
       
         else if ( ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        
        {
            
            
            totalCost = (tax * MilesK30) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK30);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK30 + totalCost);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
            
            
        }
        
        else if (((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        {
            
           
                    totalCost = (tax *(MilesK30)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK30 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK30 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        
        
        else if ( ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        {
            
             totalCost = (tax * MilesK30) / 100;
                    String sTax = String.format("RS %.2f", totalCost - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK30);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK30 + totalCost - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK30)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK30 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK30 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
       
      else  if (((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")) )
                {
                    totalCost = (tax * (MilesK8 + eco)) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK8 + eco);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK8 + totalCost + eco);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL");
                }
        
        
        else if (((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")))
        {
            
           
                    totalCost = (tax *(MilesK8)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK8 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK8 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        else if ( ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")))
        {
            
             totalCost = (tax * (MilesK8 + eco)) / 100;
                    String sTax = String.format("RS %.2f", (totalCost + eco) - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK8);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK8 + eco + totalCost - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK8)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK8 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK8 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
        
        else if ( ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        
        {
            
            
            totalCost = (tax *(eco + MilesK12)) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12 + eco);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK12 + totalCost +eco);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
            
            
        }
        
        else if (((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        {
            
           
                    totalCost = (tax *(MilesK12)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK12 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        
        
        else if ( ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        {
            
             totalCost = (tax *(eco + MilesK12)) / 100;
                    String sTax = String.format("RS %.2f", totalCost + eco - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK12 + totalCost +eco - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK12)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK12 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
       
         else if ( ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        
        {
            
            
            totalCost = (tax * (eco +MilesK20) ) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", eco + MilesK20);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK20 + eco + totalCost);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
            
            
        }
        
        else if (((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        {
            
           
                    totalCost = (tax *(MilesK20)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK12 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        
        
        else if ( ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        {
            
             totalCost = (tax * ( eco + MilesK20)) / 100;
                    String sTax = String.format("RS %.2f", totalCost - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK20 + eco);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK20 + eco +totalCost - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK20)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK20 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK20 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
       
         else if ( ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        
        {
            
            
            totalCost = (tax * ( eco +MilesK30) ) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK30  + eco );
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", eco +  MilesK30 + totalCost);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
            
            
        }
        
        else if (((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        {
            
           
                    totalCost = (tax *(MilesK30)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK30 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK30 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        
        
        else if ( ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        {
            
             totalCost = (tax * ( eco + MilesK30) ) / 100;
                    String sTax = String.format("RS %.2f", totalCost  + eco - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK30 + eco);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK30 + eco + totalCost - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK30)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK30 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK30 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
       
       else if (((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")) )
                {
                    totalCost = (tax *( fclass + MilesK8) ) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", fclass + MilesK8);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK8 + fclass + totalCost);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL");
                }
        
        
        else if (((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")))
        {
            
           
                    totalCost = (tax *(MilesK8)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK8 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK8 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        else if ( ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")))
        {
            
             totalCost = (tax * ( fclass + MilesK8) ) / 100;
                    String sTax = String.format("RS %.2f",  fclass + totalCost - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", fclass + MilesK8);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK8 + totalCost  + fclass + - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Kolkata")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK8)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK8 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK8 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
        
        else if ( ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        
        {
            
            
            totalCost = (tax * ( fclass + MilesK12) ) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", fclass + MilesK12);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", fclass + MilesK12 + totalCost);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
            
            
        }
        
        else if (((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        {
            
           
                    totalCost = (tax *(MilesK12)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK12 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        
        
        else if ( ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        {
            
             totalCost = (tax *  (fclass + MilesK12) )/ 100;
                    String sTax = String.format("RS %.2f", totalCost - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", fclass + MilesK12);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", fclass + MilesK12 + totalCost - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Mumbai")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK12)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK12 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
       
         else if ( ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        
        {
            
            
            totalCost = (tax *  (fclass + MilesK20)) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK20);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  MilesK20 + totalCost);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
            
            
        }
        
        else if (((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        {
            
           
                    totalCost = (tax *(MilesK20)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK12 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK12 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        
        
        else if ( ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        {
            
             totalCost = (tax * ( fclass +MilesK20)) / 100;
                    String sTax = String.format("RS %.2f", totalCost - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f",fclass + MilesK20);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", fclass + MilesK20 + totalCost - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Ajmer")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK20)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK20 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK20 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
       
         else if ( ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        
        {
            
            
            totalCost = (tax * ( fclass +MilesK30)) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f",fclass + MilesK30);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", fclass + MilesK30 + totalCost);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
            
            
        }
        
        else if (((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        {
            
           
                    totalCost = (tax *(MilesK30)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK30 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", ( MilesK30 + totalCost)*2);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("ONE");
                    jC.setText("NIL"); 
            
              
            
        }
        
        
        
        else if ( ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        {
            
             totalCost = (tax * (  fclass +MilesK30)) / 100;
                    String sTax = String.format("RS %.2f", totalCost - 18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", fclass + MilesK30);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f",  fclass + MilesK30 + totalCost - 18);
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("ONE WAY");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
             
            
        }
        
        else if ( ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected())
                && jCB.getSelectedItem().equals("Pune")))
        
        
        {
            
            
                    totalCost = (tax *(MilesK30)* 2) / 100;
                    String sTax = String.format("RS %.2f", totalCost -18);
                    jblTax.setText(sTax);
                    String subTotal = String.format("RS %.2f", MilesK30 * 2);
                    jblSubTotal.setText(subTotal);
                    String Total  = String.format("RS %.2f", (( MilesK30 + totalCost)*2 -18 ));
                    jblTotal.setText(Total);
                    jPrice.setText(Total);
                    jSTD.setText("STD");
                    jType.setText("RETURN");
                    jA.setText("NIL");
                    jC.setText("ONE"); 
            
           
        }
       
            
        
     
    
        
    }                                      

    private void jRbAdultYesActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Train().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField jA;
    private javax.swing.JTextField jC;
    private javax.swing.JComboBox<String> jCB;
    private javax.swing.JTextField jDate;
    private javax.swing.JTextField jFrom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPrice;
    private javax.swing.JRadioButton jRbAdultYes;
    private javax.swing.JRadioButton jRbChildYes;
    private javax.swing.JRadioButton jRbEco;
    private javax.swing.JRadioButton jRbFirst;
    private javax.swing.JRadioButton jRbReturn;
    private javax.swing.JRadioButton jRbSingle;
    private javax.swing.JRadioButton jRbStd;
    private javax.swing.JTextField jRoute;
    private javax.swing.JTextField jSTD;
    private javax.swing.JTextField jTicketNo;
    private javax.swing.JTextField jTime;
    private javax.swing.JTextField jTo;
    private javax.swing.JTextField jType;
    private javax.swing.JTextField jblSubTotal;
    private javax.swing.JTextField jblTax;
    private javax.swing.JTextField jblTotal;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    // End of variables declaration                   
}

